export const metadata = {
  title: 'Provinces - Raja Ongkir',
  description: 'Generated by create next app',
};

export default function Layout({ children }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
